import { readFileSync } from 'node:fs';

export const COLORS = ['blue', 'green', 'yellow', 'pink'];
export const SUIT_LABELS = { blue: '파랑', green: '초록', yellow: '노랑', pink: '분홍', sub: '잠수함' };
const R = (type, options = {}) => ({ type, ...options }); const C = (suit, rank) => ({ suit, rank });
// mission_cards.csv의 행 순서와 대응한다. 표시 문구와 인원별 난이도는 CSV에서 읽는다.
const MISSION_RULES = [
  R('avoidRanks',{ranks:[9]}),R('winFirstRange',{through:2}),R('winCards',{cards:[C('sub',3)]}),R('winCards',{cards:[C('green',6)]}),R('winCards',{cards:[C('yellow',1)]}),R('suitCountCompare',{left:'pink',right:'green'}),R('winCards',{cards:[C('blue',4)]}),R('streak',{amount:2}),R('winCards',{cards:[C('pink',3)]}),R('suitCountCompare',{left:'yellow',right:'blue'}),
  R('firstTrick'),R('avoidSuits',{suits:['sub']}),R('noWinFirstRange',{through:4}),R('avoidRanks',{ranks:[5]}),R('noWinFirstRange',{through:3}),R('playRankWinRank',{playedRank:7,targetRank:5}),R('noLeadSuits',{suits:['green','pink']}),R('avoidRanks',{ranks:[1]}),R('exactTricks',{amount:2}),R('minRankCards',{rank:7,amount:2}),
  R('avoidSuits',{suits:['pink']}),R('winCards',{cards:[C('pink',1),C('green',7)]}),R('captainCompare',{comparison:'less'}),R('avoidSuits',{suits:['yellow']}),R('avoidSuits',{suits:['green']}),R('winCards',{cards:[C('green',5),C('blue',8)]}),R('captainCompare',{comparison:'more'}),R('winCards',{cards:[C('pink',5),C('yellow',6)]}),R('winCards',{cards:[C('pink',8),C('blue',5)]}),R('allPlayersCompare',{comparison:'least'}),
  R('winCards',{cards:[C('blue',6),C('yellow',7)]}),R('allPlayersCompare',{comparison:'most'}),R('noWinFirstRange',{through:5}),R('minSuitCards',{suit:'pink',amount:5}),R('exactRankCards',{rank:9,amount:2}),R('trickSuitCountEqual',{suits:['pink','yellow']}),R('playRankWin',{rank:6}),R('winCards',{cards:[C('pink',9),C('yellow',8)]}),R('trickSuitCountEqual',{suits:['green','yellow']}),R('winCards',{cards:[C('yellow',9),C('blue',7)]}),
  R('winCards',{cards:[C('blue',1),C('blue',2),C('blue',3)]}),R('trickAllRanks',{comparison:'less',value:7,noSub:true}),R('playRankWinRank',{playedRank:6,targetRank:6,otherSuit:true}),R('trickAllRanks',{comparison:'greater',value:5}),R('atLeastEverySuit'),R('streak',{amount:3}),R('winFirstRange',{through:3}),R('playRankWin',{rank:5}),R('exactTricks',{amount:4}),R('trickParity',{parity:'odd',coloredOnly:true}),
  R('trickParity',{parity:'even',coloredOnly:true}),R('lastTrick'),R('exactTricks',{amount:1}),R('noStreak',{amount:2}),R('declaredTricks',{visibility:'public'}),R('avoidRanks',{ranks:[8,9]}),R('exactConsecutiveTricks',{amount:2}),R('exactSuitCards',{suit:'sub',amount:1,submarineRestrictions:[[1,2,3,4]]}),R('exactSuitCardsWithCard',{suit:'sub',amount:1,card:C('sub',1),submarineRestrictions:[[1,4],[1,2,3]]}),R('avoidRanks',{ranks:[1,2,3]}),
  R('minSuitCards',{suit:'yellow',amount:7}),R('avoidSuits',{suits:['yellow','green']}),R('avoidSuits',{suits:['pink','blue']}),R('submarineWinCard',{card:C('pink',7)}),R('exactSuitCardsWithCard',{suit:'sub',amount:1,card:C('sub',2),submarineRestrictions:[[2,4],[1,2,3]]}),R('submarineWinCard',{card:C('green',9)}),R('exactSuitCards',{suit:'pink',amount:1}),R('exactSuitCards',{suit:'sub',amount:2,submarineRestrictions:[[2,3,4]]}),R('trickRankSum',{comparison:'less',valueByPlayers:{3:8,4:12,5:16},noSub:true}),R('merged'),
  R('merged'),R('trickRankSumIn',{values:[22,23],noSub:true}),R('exactConsecutiveTricks',{amount:3}),R('trickRankSum',{comparison:'greater',valueByPlayers:{3:23,4:28,5:31},noSub:true}),R('merged'),R('merged'),R('exactRankCards',{rank:6,amount:3}),R('winCards',{cards:[C('green',3),C('yellow',4),C('yellow',5)]}),R('firstAndLast'),R('exactSuitCards',{suit:'blue',amount:2}),
  R('exactSuitCards',{suit:'sub',amount:3,submarineRestrictions:[[1,2,3,4]]}),R('exactSuitCards',{suit:'green',amount:2}),R('minRankCards',{rank:9,amount:3}),R('playRankWin',{rank:3}),R('moreThanAllOthers'),R('allCardsOfOneColor'),R('winCards',{cards:[C('blue',3),C('green',3),C('yellow',3),C('pink',3)]}),R('playRankWin',{rank:2}),R('lastWinCard',{card:C('green',2)}),R('minRankCards',{rank:5,amount:3}),
  R('playRankWinRank',{playedRank:4,targetRank:8}),R('noLeadSuits',{suits:['yellow','pink','blue']}),R('onlyFirstTrick'),R('exactTricks',{amount:0}),R('captainCompare',{comparison:'same',captainCannotOwn:true}),R('declaredTricks',{visibility:'secret'}),R('exactSuitCounts',{counts:{pink:1,green:1}}),R('onlyLastTrick'),R('suitCountEqual',{suits:['pink','yellow'],nonZero:true}),R('winCards',{cards:[C('blue',9),C('green',9),C('yellow',9),C('pink',9)]})
];
function parseCsv(text) { const rows=[]; let row=[],field='',quoted=false; for(let i=0;i<text.length;i+=1){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+=ch;i+=1;}else quoted=false;}else field+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field='';}else if(ch==='\n'){row.push(field.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=ch;}if(field||row.length){row.push(field);rows.push(row);}return rows; }
const difficulty = (value) => /^\d+$/.test(value) ? Number(value) : null;
const rows = parseCsv(readFileSync(new URL('../mission_cards.csv', import.meta.url), 'utf8').replace(/^\uFEFF/, '')).slice(1);
if(rows.length!==MISSION_RULES.length) throw new Error(`미션 규칙 ${MISSION_RULES.length}개와 CSV ${rows.length}개가 일치하지 않습니다.`);
const MERGED_CARD_ROWS = new Map([[68, [68, 69, 70]], [73, [73, 74, 75]]]);
const MERGED_ROW_INDEXES = new Set([...MERGED_CARD_ROWS.values()].flat());
export const TASK_CATALOG=rows.flatMap(([label,three,four,five],index)=>{
  const group = MERGED_CARD_ROWS.get(index);
  if (MERGED_ROW_INDEXES.has(index) && !group) return [];
  if (!group) return [{id:`mission-${String(index+1).padStart(3,'0')}`,label,difficulty:[difficulty(three),difficulty(four),difficulty(five)],...MISSION_RULES[index]}];
  const playerLabels = group.map((rowIndex) => rows[rowIndex][0]);
  return [{id:`mission-${String(index+1).padStart(3,'0')}`,label:playerLabels[0],labelByPlayerCount:{3:playerLabels[0],4:playerLabels[1],5:playerLabels[2]},difficulty:group.map((rowIndex, playerIndex) => difficulty(rows[rowIndex][playerIndex + 1])),...MISSION_RULES[index]}];
});

const STAGE_RULES={6:{allTasksToOne:true},8:{dominanceRank:9},9:{communication:'currents'},10:{allTasksToOne:true,communication:'preGame'},11:{communication:'nitrogen'},12:{forbidLeadSuits:['sub','pink']},13:{allTasksToOne:true,communication:'preGame'},14:{communication:'currents'},15:{communication:'nitrogen'},16:{communication:'none'},17:{selectionMode:'free'},19:{captainHighestTask:true},20:{communication:'variable'},21:{dominanceRank:1,communication:'variable'},23:{firstWinnerAlwaysAhead:true,communication:'afterFirstTrick'},24:{communication:'variable'},25:{captainSkipsTask:true,communication:'variable'},26:{communication:'variable'},27:{lastPlayCard:C('yellow',5)},28:{selectionMode:'free'},29:{selectionMode:'free'},30:{selectionMode:'free'},31:{selectionMode:'free'},32:{fixedTaskIds:['mission-094','mission-073','mission-008','mission-079']}};
const bookRows=parseCsv(readFileSync(new URL('../book.csv',import.meta.url),'utf8').replace(/^\uFEFF/,'')).slice(1);
if(bookRows.length!==32)throw new Error(`스테이지북 ${bookRows.length}개가 필요합니다.`);
export const STAGES=bookRows.map(([stage,difficulty,note='',sonarConstraint=''])=>({stage:Number(stage),difficulty:/^\d+$/.test(difficulty)?Number(difficulty):null,note,sonarConstraint,communication:'normal',...(STAGE_RULES[Number(stage)]??{})}));
export function missionForStage(stage,playerCount,random=Math.random){const mission=STAGES.find((item)=>item.stage===Number(stage))??STAGES[0];let communication=mission.communication;if(communication==='variable'){const roll=random();communication=roll<1/3?'normal':roll<2/3?'currents':'none';}return {...mission,communication,playerCount};}
export function createDeck(){return[...COLORS.flatMap((suit)=>Array.from({length:9},(_,index)=>({id:`${suit}-${index+1}`,suit,rank:index+1}))),...Array.from({length:4},(_,index)=>({id:`sub-${index+1}`,suit:'sub',rank:index+1}))];}
export function shuffle(cards,random=Math.random){const copy=[...cards];for(let index=copy.length-1;index>0;index-=1){const next=Math.floor(random()*(index+1));[copy[index],copy[next]]=[copy[next],copy[index]];}return copy;}
export function cardWins(candidate,current,leadSuit){if(candidate.suit==='sub'&&current.suit!=='sub')return true;if(candidate.suit!=='sub'&&current.suit==='sub')return false;if(candidate.suit===current.suit)return candidate.rank>current.rank;return candidate.suit===leadSuit&&current.suit!==leadSuit;}
export function trickWinner(plays){if(!plays.length)return null;const leadSuit=plays[0].card.suit;return plays.reduce((winner,play)=>cardWins(play.card,winner.card,leadSuit)?play:winner);}
export function mustFollow(hand,leadSuit){return leadSuit!=='sub'&&hand.some((card)=>card.suit===leadSuit);}export function canPlayCard(hand,card,leadSuit){if(!leadSuit||!mustFollow(hand,leadSuit))return true;return card.suit==='sub'||card.suit===leadSuit;}
export function timedPlayOptions(hand,leadSuit){const matching=leadSuit?hand.filter((card)=>card.suit===leadSuit):[];if(matching.length)return matching;const subs=hand.filter((card)=>card.suit==='sub');return subs.length?subs:hand;}export function timedPlayCard(hand,leadSuit,random=Math.random){const options=timedPlayOptions(hand,leadSuit);return options.length?options[Math.floor(random()*options.length)]:null;}
export function taskDifficulty(task,playerCount){return task.difficulty[playerCount-3]??null;}export function taskPassBudget(playerCount,taskCount){return playerCount*Math.ceil(taskCount/playerCount)-taskCount;}export function taskEligible(task,playerCount,hands){if(!Number.isInteger(taskDifficulty(task,playerCount)))return false;if(!task.submarineRestrictions||!hands)return true;return !Object.values(hands).some((hand)=>task.submarineRestrictions.some((ranks)=>ranks.every((rank)=>hand.some((card)=>card.suit==='sub'&&card.rank===rank))));}export function drawTasks(playerCount,target,hands){const eligible=TASK_CATALOG.filter((task)=>taskEligible(task,playerCount,hands));const chosen=[];let total=0;for(const task of shuffle(eligible)){const value=taskDifficulty(task,playerCount);if(total+value>target)continue;chosen.push({...task,label:task.labelByPlayerCount?.[playerCount]??task.label,value:task.valueByPlayers?.[playerCount]??task.value,ownerId:null,declaredTricks:null});total+=value;if(total===target)return chosen;}return chosen;}
export function tasksByIds(playerCount,ids,hands){return ids.map((id)=>TASK_CATALOG.find((task)=>task.id===id)).map((task)=>{if(!task||!taskEligible(task,playerCount,hands))throw new Error(`고정 과제 ${task?.id??'없음'}을 사용할 수 없습니다.`);return {...task,label:task.labelByPlayerCount?.[playerCount]??task.label,value:task.valueByPlayers?.[playerCount]??task.value,ownerId:null,declaredTricks:null};});}

const cardsOf=(trick)=>trick.cards??[];const playsOf=(trick)=>trick.plays??[];const ownerTricks=(state,id)=>state.trickHistory.filter((trick)=>trick.winnerId===id);const wonCards=(state,id)=>(state.won[id]??[]).flat();const count=(cards,predicate)=>cards.filter(predicate).length;const final=(state)=>Boolean(state.finished);const compare=(left,right,type)=>type==='less'?left<right:type==='more'?left>right:left===right;const hasCard=(trick,target)=>cardsOf(trick).some((card)=>card.suit===target.suit&&card.rank===target.rank);const exact=(value,target,state)=>value>target?'failed':final(state)?value===target?'complete':'failed':'active';
const maxStreak=(state,id)=>state.trickHistory.reduce((result,trick)=>{const current=trick.winnerId===id?result.current+1:0;return{current,max:Math.max(result.max,current)};},{current:0,max:0}).max;
function required(cards,state,id){for(const target of cards){const captured=state.trickHistory.find((trick)=>hasCard(trick,target));if(captured&&captured.winnerId!==id)return'failed';}return cards.every((target)=>state.trickHistory.some((trick)=>trick.winnerId===id&&hasCard(trick,target)))?'complete':final(state)?'failed':'active';}
const matching=(state,id,predicate)=>ownerTricks(state,id).some((trick)=>predicate(cardsOf(trick),playsOf(trick),trick));
export function taskStatus(task,state,id){const tricks=ownerTricks(state,id),won=wonCards(state,id),history=state.trickHistory;
  if(task.type==='winCard')return required([C(task.suit,task.rank)],state,id);if(task.type==='winCards')return required(task.cards,state,id);
  if(task.type==='avoidRanks')return won.some((card)=>task.ranks.includes(card.rank))?'failed':final(state)?'complete':'active';if(task.type==='avoidSuits')return won.some((card)=>task.suits.includes(card.suit))?'failed':final(state)?'complete':'active';
  if(task.type==='winFirstRange'){for(let i=0;i<Math.min(task.through,history.length);i+=1)if(history[i].winnerId!==id)return'failed';return history.length>=task.through?'complete':'active';}if(task.type==='noWinFirstRange'){if(history.slice(0,task.through).some((trick)=>trick.winnerId===id))return'failed';return history.length>=task.through?'complete':'active';}
  if(task.type==='firstTrick')return history.length?(history[0].winnerId===id?'complete':'failed'):'active';if(task.type==='lastTrick')return final(state)?(history.at(-1)?.winnerId===id?'complete':'failed'):'active';if(task.type==='lastWinCard')return final(state)?(history.at(-1)?.winnerId===id&&hasCard(history.at(-1),task.card)?'complete':'failed'):'active';if(task.type==='firstAndLast')return final(state)?(history[0]?.winnerId===id&&history.at(-1)?.winnerId===id?'complete':'failed'):'active';
  if(task.type==='exactTricks')return exact(tricks.length,task.amount,state);if(task.type==='declaredTricks')return task.declaredTricks===null?'active':exact(tricks.length,task.declaredTricks,state);if(task.type==='onlyFirstTrick'||task.type==='onlyLastTrick'){const status=exact(tricks.length,1,state);if(status!=='complete')return status;return(task.type==='onlyFirstTrick'?history[0]:history.at(-1))?.winnerId===id?'complete':'failed';}
  if(task.type==='streak')return maxStreak(state,id)>=task.amount?'complete':final(state)?'failed':'active';if(task.type==='noStreak')return maxStreak(state,id)>=task.amount?'failed':final(state)?'complete':'active';if(task.type==='exactConsecutiveTricks'){const status=exact(tricks.length,task.amount,state);if(status!=='complete')return status;const positions=history.map((trick,index)=>trick.winnerId===id?index:-1).filter((index)=>index>=0);return positions.every((position,index)=>index===0||position===positions[index-1]+1)?'complete':'failed';}
  if(task.type==='minRankCards')return count(won,(card)=>card.suit!=='sub'&&card.rank===task.rank)>=task.amount?'complete':final(state)?'failed':'active';if(task.type==='exactRankCards')return exact(count(won,(card)=>card.suit!=='sub'&&card.rank===task.rank),task.amount,state);if(task.type==='minSuitCards')return count(won,(card)=>card.suit===task.suit)>=task.amount?'complete':final(state)?'failed':'active';if(task.type==='exactSuitCards')return exact(count(won,(card)=>card.suit===task.suit),task.amount,state);
  if(task.type==='exactSuitCardsWithCard'){const status=exact(count(won,(card)=>card.suit===task.suit),task.amount,state);return status==='complete'?(won.some((card)=>card.suit===task.card.suit&&card.rank===task.card.rank)?'complete':'failed'):status;}if(task.type==='exactSuitCounts'){const results=Object.entries(task.counts).map(([suit,amount])=>exact(count(won,(card)=>card.suit===suit),amount,state));return results.includes('failed')?'failed':results.every((item)=>item==='complete')?'complete':'active';}
  if(task.type==='suitCountCompare')return final(state)?(count(won,(card)=>card.suit===task.left)>count(won,(card)=>card.suit===task.right)?'complete':'failed'):'active';if(task.type==='suitCountEqual'){const left=count(won,(card)=>card.suit===task.suits[0]),right=count(won,(card)=>card.suit===task.suits[1]);return final(state)?(left===right&&(!task.nonZero||left>0)?'complete':'failed'):'active';}
  if(task.type==='captainCompare'){if(task.captainCannotOwn&&id===state.captainId)return'failed';return final(state)?(compare(tricks.length,ownerTricks(state,state.captainId).length,task.comparison)?'complete':'failed'):'active';}if(task.type==='allPlayersCompare'){if(!final(state))return'active';const others=Object.keys(state.won).filter((other)=>other!==id).map((other)=>ownerTricks(state,other).length);return task.comparison==='most'?(tricks.length>Math.max(...others)?'complete':'failed'):(tricks.length<Math.min(...others)?'complete':'failed');}if(task.type==='moreThanAllOthers')return final(state)?(tricks.length>Object.keys(state.won).filter((other)=>other!==id).reduce((sum,other)=>sum+ownerTricks(state,other).length,0)?'complete':'failed'):'active';
  if(task.type==='atLeastEverySuit')return COLORS.every((suit)=>won.some((card)=>card.suit===suit))?'complete':final(state)?'failed':'active';if(task.type==='allCardsOfOneColor')return COLORS.some((suit)=>count(won,(card)=>card.suit===suit)===9)?'complete':final(state)?'failed':'active';if(task.type==='noLeadSuits')return history.some((trick)=>trick.plays?.[0]?.playerId===id&&task.suits.includes(trick.plays[0].card.suit))?'failed':final(state)?'complete':'active';
  if(task.type==='playRankWin')return matching(state,id,(_,plays)=>plays.some((play)=>play.playerId===id&&play.card.rank===task.rank))?'complete':final(state)?'failed':'active';if(task.type==='playRankWinRank')return matching(state,id,(cards,plays)=>plays.some((play)=>play.playerId===id&&play.card.rank===task.playedRank)&&cards.some((card)=>card.rank===task.targetRank&&(!task.otherSuit||plays.some((play)=>play.playerId===id&&play.card.rank===task.playedRank&&play.card.suit!==card.suit))))?'complete':final(state)?'failed':'active';if(task.type==='submarineWinCard')return matching(state,id,(cards,plays)=>hasCard({cards},task.card)&&plays.some((play)=>play.playerId===id&&play.card.suit==='sub'))?'complete':final(state)?'failed':'active';
  if(task.type==='trickSuitCountEqual'||task.type==='balancedTrick'){const suits=task.suits;return matching(state,id,(cards)=>{const [left,right]=suits.map((suit)=>count(cards,(card)=>card.suit===suit));return left>0&&right>0&&left===right;})?'complete':final(state)?'failed':'active';}if(task.type==='trickAllRanks')return matching(state,id,(cards)=>(!task.noSub||cards.every((card)=>card.suit!=='sub'))&&cards.every((card)=>compare(card.rank,task.value,task.comparison)))?'complete':final(state)?'failed':'active';
  if(task.type==='trickRankSum'||task.type==='trickRankSumIn')return matching(state,id,(cards)=>{const sum=cards.reduce((total,card)=>total+card.rank,0);return(!task.noSub||cards.every((card)=>card.suit!=='sub'))&&(task.type==='trickRankSumIn'?task.values.includes(sum):compare(sum,task.value,task.comparison));})?'complete':final(state)?'failed':'active';if(task.type==='trickParity'||task.type==='parityTrick'){const parity=task.parity==='odd'?1:0;return matching(state,id,(cards)=>{const scoped=task.coloredOnly?cards.filter((card)=>card.suit!=='sub'):cards;return scoped.length>0&&scoped.every((card)=>card.rank%2===parity);})?'complete':final(state)?'failed':'active';}
  if(task.type==='mostSuitInTrick')return matching(state,id,(cards)=>{const amounts=Object.fromEntries(COLORS.map((suit)=>[suit,count(cards,(card)=>card.suit===suit)]));return amounts[task.suit]>0&&amounts[task.suit]===Math.max(...Object.values(amounts));})?'complete':final(state)?'failed':'active';if(task.type==='twoSuitsTrick')return matching(state,id,(cards)=>new Set(cards.filter((card)=>card.suit!=='sub').map((card)=>card.suit)).size>=2)?'complete':final(state)?'failed':'active';return'active';}
export function taskSetStatus(tasks,state){const statuses=tasks.map((task)=>task.ownerId?taskStatus(task,state,task.ownerId):'unassigned');const failedIndex=statuses.findIndex((status)=>status==='failed');return{statuses,failedTask:failedIndex<0?null:tasks[failedIndex],allComplete:tasks.length>0&&statuses.every((status)=>status==='complete')};}
export function communicationPosition(hand,card){if(card.suit==='sub')return null;const same=hand.filter((candidate)=>candidate.suit===card.suit);if(same.length===1)return'only';const ranks=same.map((candidate)=>candidate.rank);if(card.rank===Math.max(...ranks))return'high';if(card.rank===Math.min(...ranks))return'low';return null;}export function displayCard(card){return`${SUIT_LABELS[card.suit]} ${card.rank}`;}
